# schedule
day1: Tuesdays
time1: 6 - 8 PM
loc1: <strong>BA1170</strong> - <em>Bahen Centre for Information Technology</em>

day2: Tuesdays
time2: 6 - 8 PM
loc2: <strong>BA1170</strong> - <em>Bahen Centre for Information Technology</em>

dayTut: TBA
timeTut: TBA
locTut: TBA

start_date: May 6, 2025
start_description: Please note that the lecture halls are different in Tuesdays and Thursdays.

# Site settings
course_name: Deep Generative Models
course_description: "This course aims to build a good understanding on Generative Models, the state-of-the-art architectures and their applications. The course in designed in two major parts, where in the first part the basic idea of data generation is introduced, and some mathematical foundations are provided. In this respect, the course looks at <em>Large Language Models</em> as an initial generative model and discusses some advancement in this respect. The second part of the course gets into the three major approaches for designing a generative model: namely, <em>generative adversarial networks (GANs), variational autoencoders (VAEs), and diffusion models.</em> The course finally goes through some recent advancements in generative AI. To follow the contents of this course, the students need to have a good understanding of machine learning models, particularly neural networks. Knowledge in more advanced topics like unsupervised learning methods, or newer architectures will be given in the course throughout the semester. A primary course in Machine Learning has hence been considered as the prerequisite. It is expected that the second part of the course dominates, i.e., approximately half of lectures will be on deep generative models."
course_semester: "Summer 2025"


assgn_mark: 45%
assgn_desc: "3 assignment sets"
assgn_txt: "This is the most important part: <em>there is no way to learn a topic like Generative Models unless we get our hands dirty and implement whatever we learn.</em> Roughly speaking, the first one goes through basics and make you play around with language models. The next two go through go through different ideas for data generation, i.e., GAN, VAE and Diffusion. The assignments include both analytic and programming tasks and count roughly for 45% of your final mark."

# Attention 	The assignments are a part of learning procedure. This means that they are prerequisites for understanding next parts! When solving them please pay attention to the Code of Honor!

exam_mark: 25%
exam_desc: "midterm exam"
exam_txt: "In the middle of the semester, somewhere around Week 7, there will be an exam. The exam will ask questions on theory. There will be no programming questions in the exam. The exam evaluates the understanding of fundamental concepts through questions that can be either explained in words or solved by hand. This exam will comprise 25% of the total mark."

project_mark: 30%
project_desc: "predefined project from the list of suggestions or open-ended"
project_txt: "The course project procedure is illustrated in a seperate page. In a nutshell, however, the project will be in groups. Each group selects a topic from the predefined project list. Each group will then work on the project through the semester and present its final result at the end in a report and a short presentation. You have the option to choose your topic. In this case, your topic should be confirmed by the instructor and your project work description should be prepared to prepare to that of predefined ones. The course project is the key evaluator and comprises 30% of the course work."


baseurl: "/genai-utoronto" # the subpath of your site, e.g. /blog/
url: "https://bereyhi-courses.github.io/" # the base hostname & protocol for your site

schoolname: "University of Toronto"
schoolurl: "https://www.ece.utoronto.ca"
personal_page: "bereyhi.com"

address: |
    The Edward S. Rogers Sr. Department of Electrical and Computer Engineering
    University of Toronto

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

minima:
  include_css:
    - /assets/css/custom.css

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include:
  - assets
  - _images
  - _css

exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
